export enum FoodItemActions {
    NEW_FOODITEM= "NEW-FOOD-ITEM",
    NEW_FOODITEM_FAILURE = "NEW-FOODITEM-FAILURE",
    ALL_FOODITEMS = "ALL-FOODITEMS",
    ALL_FOODITEMS_FAILURE = "ALL-FOODITEMS-FAILURE",
  }
  